### ISSUE TITLE
[BUG] Update require statement in README for Creating the OAuth Authorization Header

### ISSUE THREAD

**Issue by devonh-block** [Mastercard/oauth1-signer-ruby#23]
With the new namespace changes, I believe the `require 'oauth'` statement needs to be updated to `require 'mastercard/oauth'`.

**Comment by joseph-neeraj** [comment]
hi @devonh-block thank you for bringing this to our notice. This has been fixed now.

**Comment by danny-gallagher** [comment]
Thanks @joseph-neeraj, Closing the issue
